#
# Copyright 2011-2025 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx/blob/master/LICENSE
#

SRC_DIR=..
RUNTIME_DIR=$(SRC_DIR)/runtime
BUILD_DIR=../../.build

include $(BGFX_DIR)/scripts/shader.mk
